-- CreateEnum
CREATE TYPE "Level" AS ENUM ('BEGINNER', 'INTERMEDIATE', 'ADVANCED');

-- AlterTable
ALTER TABLE "Course" ADD COLUMN     "duration" TEXT NOT NULL DEFAULT '6 weeks',
ADD COLUMN     "level" "Level" NOT NULL DEFAULT 'BEGINNER',
ADD COLUMN     "price" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "rating" DOUBLE PRECISION NOT NULL DEFAULT 4.5,
ADD COLUMN     "studentsCount" INTEGER NOT NULL DEFAULT 0;
